
sonar.projectKey=ressources-relationnelles-cda-2026_Ressources-Relationnelles-Front
sonar.organization=ressources-relationnelles-cda-2026
sonar.projectName=ressources-relationnelles

sonar.sourceEncoding=UTF-8
sonar.sources=app,components,hooks,services
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**

