
sonar.projectKey=ressources-relationnelles-CDA-2026_Ressources-Relationnelles-Front
sonar.organization=ressources-relationnelles-cda-2026
sonar.projectName=Ressources-Relationnelles-Front

sonar.sourceEncoding=UTF-8
sonar.sources=app,components,hooks,services
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**


sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx,tests/**/*.spec.ts,tests/**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

