
name: Front - Tests


on:
  push:
    branches:
      - dev
      - main
      
  pull_request:
    branches:
      - dev
      - main



jobs:

  tests:
    name: Tests unitaires Jest
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installation des dépendances
        run: npm ci

      - name: Tests unitaires avec couverture
        run: npm run test:coverage

      - name: Conserver le rapport de couverture
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: coverage/

  